### ISSUE TITLE
Bug: Deleting when being offline

### ISSUE THREAD

**Issue by vandres** [GetDutchie/brick#182]
Hi.

When tying to delete a model when being offline, an exception is thrown. Syncing still works, after going back online.

When upserting a model while being offline, no error is thrown.

**Comment by tshedor** [comment]
Hi @vandres if you always need to throw an error, try using [`reattemptForStatusCodes`](https://github.com/greenbits/brick/blob/master/packages/brick_offline_first/lib/src/offline_first_with_rest/offline_first_with_rest_repository.dart#L142-L144).

However, I would advise that this is an antipattern and should be used rarely. By name, the OfflineFirst system is designed to always deliver data from offline first. Whether the application is online or offline should not affect data handling.

**Comment by vandres** [comment]
I agree. There should be no error when deleting either

**Comment by tshedor** [comment]
@vandres to clarify, you're suggesting that when the application does has internet connectivity and cannot reach the REST endpoint to delete, no error should be reported to the application?

**Comment by vandres** [comment]
@tshedor In my opinion, all write operations should behave the same. Either they both report an error, or they both deliver the same offline first experience. I would prefer the latter. 

What is your opinion about that? What are/were the thoughts behind the current implementation?

**Comment by pkozlovskiy** [comment]
@vandres one way is to add flag to your model 'isDeleted' and upsert changes.

**Comment by tshedor** [comment]
Hey @vandres I hope I addressed this in #263 and Brick 2. Please let me know if using `OfflineFirstDeletePolicy.requireRemote` doesn't resolve your problem.
