### ISSUE TITLE
FR/Bug: `enumAsString` should also be available for SQLite

### ISSUE THREAD

**Issue by vandres** [GetDutchie/brick#184]
Currently `enumAsString` is only available for `@Rest()`. In my opinion, this should also be available for `@Sqlite()`. It should convert the column to a `varchar` and save the string.

Also my opinion :) In general I would not recommend to use an integer representation of an Enum. When adding options to an Enum, you would always need to add it at the end. Otherwise the index will be changed and you would need to migrate the saved data.

**Comment by tshedor** [comment]
@vandres finally got around to adding this.
