### ISSUE TITLE
Can't generate anything since update to v2

### ISSUE THREAD

**Issue by KayoticSully** [GetDutchie/brick#273]
I'm having this weird issue. Since I've upgraded to v2 the build_runner does absolutely nothing.  It runs but has 0 outputs even after I have added a field to a model.

Are there any common issues that could cause a migration to not be created?

**Comment by tshedor** [comment]
Hi @KayoticSully have you renamed your model files to `.model.dart`? There are other [breaking changes](https://github.com/GetDutchie/brick/issues/263) in this announcement that may be useful too.

**Comment by KayoticSully** [comment]
I did rename my models. I tried to follow that migration guide best I could. I'm guessing I missed something but its odd, there are no errors, it seems like the runner runs fine but it has no outputs even though Ive changed one of the models.  Do I need to completely reset thing and delete all the previous migrations or anything?

**Comment by KayoticSully** [comment]
@tshedor I think I figured it out.  The v2 packages haven't been published to `pub.dev` yet so I wasn't actually using the new packages and since i was specifying "any" version it was still expecting models to be in the old location.  I switched over to referencing the git repo and its all working now.

**Comment by tshedor** [comment]
Hey @KayoticSully sorry about that and good catch. I'll publish the rest tomorrow.

**Comment by tshedor** [comment]
@KayoticSully I've published all `-rc` packages on pub.dev; please let me know if `build_runner` still doesn't work when sourcing from pub.dev
