### ISSUE TITLE
Question - Hive/Isar local storage support?

### ISSUE THREAD

**Issue by AbgarSim** [GetDutchie/brick#285]
Hi there! First off, thanks for the awesome library! I wish to use this lib in my application, but want to swap out SQLite with Hive for local storage. Are there any plans to provide support for any additional internal storages (Hive or maybe even Isar)? 
Thanks in advance!

**Comment by tshedor** [comment]
Hi @AbgarSim thanks for the note. There aren't plans to support anything besides SQLite for local storage. Hive has its own annotation system and plenty of complexity. PRs are always open, however, if you want to examine adding a Hive domain to within Brick.
