### ISSUE TITLE
Outdated documentation and examples

### ISSUE THREAD

**Issue by maherjaafar** [GetDutchie/brick#304]
I wanted to implement offline first with rest api in a Flutter app. I went through the Readme file to understand the package and the sub-packages and what I should use, so cloned the repo and checked the REST example.

The architecture is really good, but when I started with implementing it in Flutter. I don't know which package I should use and what are the parameters that should be used and how migrations are generated.

Also which classes would be generated and which ones I should create by myself.

**Comment by tshedor** [comment]
Hi @maherjaafar can you please be more specific about where you found outdated documentation and examples?

**Comment by maherjaafar** [comment]
@tshedor thank you for the quick answer. I edited the description of the issue.

**Comment by tshedor** [comment]
@maherjaafar A few questions for you to help me triage your problem:

> The architecture is really good, but when I started with implementing it in Flutter. I don't know which package I should use and what are the parameters that should be used...

Is [the REST example](https://github.com/GetDutchie/brick/tree/main/example) not running locally? This package is a [Flutter app](https://github.com/GetDutchie/brick/blob/main/example/lib/main.dart) and should illustrate the repository's usage within an app. That main file should show what packages to import.

> ...and how migrations are generated.
>
> Also which classes would be generated and which ones I should create by myself.

Anything with a `.g.dart` suffix is generated. The only thing you _need_ to worry about is your `.model.dart` file. I'd encourage you to review the `.migration.dart` file to make sure your migrations generated properly. But the model files are your source of truth. Your schema, `brick.g.dart` entrypoint, `adapter.g.dart` translations, those are all generated based on your `.model.dart` files. 

You should also have a `repository.dart` file to handle configuration of local and remote providers. But that file is not changed very often after the initial setup.

**Comment by maherjaafar** [comment]
I will check it out. Thank you for the good explanation. I will close this issue. 👍🏼
