### ISSUE TITLE
Build_runner runs with problems

### ISSUE THREAD

**Issue by hortigado** [GetDutchie/brick#347]
![image](https://github.com/GetDutchie/brick/assets/42924254/a21a141a-b9b2-42ab-9fb0-fc86a953d3c1)
![image](https://github.com/GetDutchie/brick/assets/42924254/0ae67b7a-19ba-46d4-ba30-b80ab51d514c)
![image](https://github.com/GetDutchie/brick/assets/42924254/937d52e8-fd09-4804-a2fa-167d1f1e3c0d)
![image](https://github.com/GetDutchie/brick/assets/42924254/f53fcdbb-20b0-48b0-b383-0f65081f5b96)

Build_runner does not correctly import models. When running build_runner It import the models incorrectly without the /models folder but below it imports them correctly. This causes the adapters to not be created correctly

**Comment by tshedor** [comment]
Hey @hortigado thanks for using Brick. I'm going to consolidate this ticket into #343 and #344 but before I do, how did you get adapters generated with `_model_adapter.g.dart` (like `sell_model` or `settings_model`)?

**Comment by hortigado** [comment]
@tshedor Hi friend. Already found what the error is due to, it is due to the relative imports. In the images we can see the difference when the request is imported without relative import, it generates the error.
![image](https://github.com/GetDutchie/brick/assets/42924254/db0a2b1d-8e27-4467-92d1-aabf346b6bd6)
![image](https://github.com/GetDutchie/brick/assets/42924254/2f6bc832-078d-49b7-b3bb-2665d0999d74)

**Comment by hortigado** [comment]
The fastest and most temporary solution would be to remove the relative imports for the brick folder. This would be achieved by creating an `analysis_options.yaml` file inside the folder and putting the following code.
```
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
```

**Comment by tshedor** [comment]
@hortigado sorry, I'm a little confused. The error you're getting is a lint error? Or you're unable to complete `flutter run` without runtime/compile errors?

**Comment by hortigado** [comment]
@tshedor  Hi, The **models**, **requests** and **adapters** in the` brick.g.dart` file are not imported correctly and the **request** file is not imported correctly in the` .adapter.dart.`
All this is due to importing the` .request.dart` as a relative import in our `.model.dart`
In a project that does not work with relative imports, there is no problem. I get the error because I work with relative imports.
import 'package:porcicultor/brick/models/age.model.request.dart'; Working
import 'balanceado.model.request.dart'; Relative Import not working

**Comment by tshedor** [comment]
@hortigado Could you just use absolute imports within model files?

**Comment by hortigado** [comment]
@tshedor correct that is the solution that I think is the simplest and I mentioned it above.
I think I will give as solved this problem. Regards
