### ISSUE TITLE
How to send the child relation to the server?

### ISSUE THREAD

**Issue by hortigado** [GetDutchie/brick#351]
Hello, this is more than an error, it is a query. How could the child relationship be sent to the server? This works locally, but only the main model is sent to the server and I think it is correct because I am establishing that only the id is put on `pizza_ids`, but there would be a way to make it automatic. This speeds up the sending of data a lot.
 For better understanding I give an example. In the image you can see how I create a `Customer `item and a `Pizza `item as a child at the same time. I want the two data to be uploaded to the server but each one to its respective table in the parent item (Customer) only the id of the child item (pizza) is saved and vice versa in the child item the id of the parent is saved.
Could you help me with an example of how to do it if possible. Thanks
![image](https://github.com/GetDutchie/brick/assets/42924254/293dfa45-4e7d-44db-82fc-4fc811bc81b0)
![image](https://github.com/GetDutchie/brick/assets/42924254/efa4b6e8-a7a7-42ec-ae01-b0de30e10deb)

**Comment by hortigado** [comment]
#115

**Comment by tshedor** [comment]
@hortigado that related ticket is exactly right. If you want to send a full payload (not just the `id`), [simply remove](https://github.com/GetDutchie/brick/issues/115#issuecomment-753660780) the `@OfflineFirst` annotation.

The full association is saved to the association's table in SQLite on `upsert`. When the association is sent to REST _while using `@OfflineFirst`_, only the key value of your `where` argument is sent.

**Comment by hortigado** [comment]
@tshedor Thanks I tried removing the `@OfflineFirst` and leaving only the `@Rest`; but when doing them it is saved correctly locally but nothing is sent to the server, not even the Customer item.

**Comment by tshedor** [comment]
@hortigado did you regenerate the adapter? Does your `CustomerRequestTransformer` have an `upsert` field?

**Comment by hortigado** [comment]
Yes, I am using a remote server (Appwrite) not the local one in the example, I don't know if this could also cause a problem
```
class CustomerRequestTransformer extends RestRequestTransformer {
  // A production code base would not forward to another operation
  // but for testing this is convenient
  @override
  RestRequest get delete => get;

  @override
  RestRequest get get {
    if (query?.where != null) {
      final byId = Where.firstByField('id', query?.where);
      print(byId.toString());
      // member endpoint
      if (byId?.value != null) {
        return RestRequest(
            url:
                "/databases/6436b61c1e67e1fe6d5d/collections/649531713e0d37be7da4/documents/${byId!.value}",
            topLevelKey: "documents");
      }
    }
    return RestRequest(
        url:
            '/databases/6436b61c1e67e1fe6d5d/collections/649531713e0d37be7da4/documents',
        topLevelKey: "documents");
  }

  // A production code base would not forward to another operation
  // but for testing this is convenient
  @override
  RestRequest get upsert {
    final id = query?.providerArgs['id'];
    final method = query?.action == QueryAction.update ? "PATCH" : "POST";
    final url = method == "PATCH"
        ? '/databases/6436b61c1e67e1fe6d5d/collections/649531713e0d37be7da4/documents/$id'
        : '/databases/6436b61c1e67e1fe6d5d/collections/649531713e0d37be7da4/documents';

    return RestRequest(
      supplementalTopLevelData: <String, String>{
        "documentId": id!.toString(),
      },
      method: method,
      url: url,
      topLevelKey: "data",
    );
  }

  RestRequest get update {
    final id = query?.providerArgs['id'];

    return RestRequest(
      supplementalTopLevelData: <String, String>{
        "documentId": id!.toString(),
      },
      method: "PATCH",
      url:
          '/databases/6436b61c1e67e1fe6d5d/collections/649531713e0d37be7da4/documents',
      topLevelKey: "data",
      /*  headers: <String, String>{
            "documentId": id,
          } */
    );
  }

  const CustomerRequestTransformer(Query? query, RestModel? instance)
      : super(query, instance);
}
```

**Comment by hortigado** [comment]
```
Future<Customer> _$CustomerFromRest(Map<String, dynamic> data,
    {required RestProvider provider,
    OfflineFirstWithRestRepository? repository}) async {
  return Customer(
      id: data['\$id'] as String?,
      firstName: data['first_name'] as String?,
      lastName: data['last_name'] as String?,
      pizzas: await Future.wait<Pizza>(data['pizzas']
              ?.map((d) => PizzaAdapter()
                  .fromRest(d, provider: provider, repository: repository))
              .toList()
              .cast<Future<Pizza>>() ??
          []));
}

Future<Map<String, dynamic>> _$CustomerToRest(Customer instance,
    {required RestProvider provider,
    OfflineFirstWithRestRepository? repository}) async {
  return {
    'first_name': instance.firstName,
    'last_name': instance.lastName,
    'pizzas': instance.pizzas!.first.id
  };
}
```

**Comment by tshedor** [comment]
@hortigado I've created a [mini example](https://github.com/GetDutchie/brick/compare/format-example...see-posts-351) to help illustrate what you'll need to do. When running the server, you'll see `upsert` request body logged. 

Based on what you have in the latest adapter code, your adapter wasn't regenerated for `toRest`. It looks like there's an override somewhere:

```dart
    'pizzas': instance.pizzas!.first.id
```

Can you supply your model code?

**Comment by hortigado** [comment]
@tshedor Thanks for the example, I had already tried the example as it is and it didn't work for me. Now I tried again and it works 100%. 
Thank you if I have another question I open a new issue
