### ISSUE TITLE
Upgrade http package

### ISSUE THREAD

**Issue by shanewow** [GetDutchie/brick#369]
Hello, I am really enjoying using this framework!

I am using brick_offline_first_with_rest 3.1.0 and getting this error while trying to add the "oidc" library:

`Because oidc >=0.2.0+1 depends on http ^1.1.0 and oidc <0.2.0+1 depends on oidc_core ^0.2.0, every version of oidc requires http ^1.1.0 or oidc_core ^0.2.0.
And because every version of oidc_core depends on http ^1.1.0 and every version of brick_offline_first_with_rest depends on http ^0.13.0,
  brick_offline_first_with_rest is incompatible with oidc.
So, because ui depends on both brick_offline_first_with_rest ^3.0.1 and oidc any, version solving failed.`

Are they any plans to do any dependency upgrades?

Thank you!!!

**Comment by hortigado** [comment]
Hi you can add the package in dependency_overrides:

**Comment by tshedor** [comment]
Hey @shanewow thanks for using Brick. [Looking at the pubspec](https://github.com/GetDutchie/brick/blob/main/packages/brick_offline_first_with_rest/pubspec.yaml) for v3.0.1, http has a very loose dependency that's >0.13 <2.0 . http 1 should be permitted in the package resolution....is the offending package definitely offline_first_with_rest or is it another one of the brick dependencies bubbling the error up?

Alternatively, you could try @hortigado quick fix of overrides, but I would like to solve this for future users of Brick.

**Comment by tshedor** [comment]
@shanewow any luck?

**Comment by shanewow** [comment]
@tshedor @hortigado I ran out of time and decided to come back to this later. I ended up implementing a different oidc library for the time being. I really appreciate you taking a look at the spec and the quick response.
