### ISSUE TITLE
Outdated package dependencies

### ISSUE THREAD

**Issue by mfrischbutter** [GetDutchie/brick#375]
Hello, I would like to try brick in my project. Unfortunately the http package is on a very old version ^0.13.0
Is an update of the dependencies due at some point?

package: brick_offline_first_with_rest
version: 3.0.1

**Comment by tshedor** [comment]
The package dependency is still very permissive (allowing http >0.13 <2.0.0) but given #369 , I'm raising the minimum to 1.0.0 in #376. 

`offline_first_with_rest` 3.0.2 has been published with this new restriction. 

@mfrischbutter If `3.0.2` solves your problem please close out this issue
