### ISSUE TITLE
Support to windows not work

### ISSUE THREAD

**Issue by hortigado** [GetDutchie/brick#377]
Hello, I was testing the package to work on Windows but it has a problem and it does not obtain the correct address in Windows  when creating the database, which can be solved with the `getApplicationSupportDirectory()` function as I show in the image
![image](https://github.com/GetDutchie/brick/assets/42924254/b722a1d2-9ce3-475f-a90a-815961fad90a)

**Comment by hortigado** [comment]
Hello, I have never created one but I hope it is good. Greetings #378

**Comment by tshedor** [comment]
Closing this issue in favor of any additional discussion on #387
