### ISSUE TITLE
Adapter file not generated when uniquely identified field is a class and no primitive

### ISSUE THREAD

**Issue by devj3ns** [GetDutchie/brick#379]
Hey folks, first, thanks a lot for creating and open-sourcing this project, I really like it so far!

In my `OfflineFirstWithRestModel`, I have a field with a custom `UUID` class for validating UUIDs. This class simply stores the `UUID` as a string inside a `value` field. So what I have done in the model is:

```
@Sqlite(
      unique: true,
      columnType: Column.varchar,
      fromGenerator: 'UUID.fromUniqueString(%DATA_PROPERTY%)',
      toGenerator: '%INSTANCE_PROPERTY%.value')
  @Rest(
      fromGenerator: 'UUID.fromUniqueString(%DATA_PROPERTY%)',
      toGenerator: '%INSTANCE_PROPERTY%.value')
final UUID id;
```

Unfortunately, with this field present in my model, the adapter `g.dart` file won't be generated. When I change the `id`s type to a `String`, it gets correctly generated.

When the adapter is built with the `id` of type `String` and I change the `id` to be a `UUID` instead, the to/fromRest/Sqlite methods of the adapter are correctly altered, but the `id` field is missing inside the `fieldsToSqliteColumns` map.

**Comment by tshedor** [comment]
Hi @devj3ns . This is a tricky part of Brick. What [you can do here is use an](https://getdutchie.github.io/brick/#/offline_first/models?id=offlinefirstserdes) `OfflineFirstSerdes`. This should also save you the copy and paste of the custom generators. 

```dart
class UUID extends OfflineFirstSerdes<String, String> {
  final String value;

  UUID(this.value);

  factory UUID.fromRest(String? data) {
    if (data == null || data.isEmpty) return null;

    return UUID(data!)
  }

  factory UUID.fromSqlite(String data) => UUID.fromRest(data);

  toRest() => value;
  toSqlite() => value;
}
```

Then, in your model code, you can just use:

```dart
@Sqlite(unique: true)
final UUID id;
```

**Comment by devj3ns** [comment]
That's exactly what I was looking/hoping for, thanks!

With this the generation mostly works, but in the `fieldsToSqliteColumns` Map in the adapter the type of the `id` SQLite column is set to `UUID` instead of `String` which results in the following exception:

`Invalid argument 399895f6-a34b-4be9-bfea-c2e2bec12de6 with type UUID. Only num, String and Uint8List are supported.`

Using `columnType: Column.varchar` and rerunning the `build_runner` does not change the adapter.

**Comment by tshedor** [comment]
@devj3ns Can you provide more of that stack trace? The `fieldsToSqliteColumns` [isn't a map](https://github.com/GetDutchie/brick/blob/main/packages/brick_sqlite/lib/src/helpers/query_sql_transformer.dart#L126) to the primitives that SQLite uses, it's more a map to [how to retrieve that type](https://github.com/GetDutchie/brick/blob/main/packages/brick_sqlite/lib/src/helpers/query_sql_transformer.dart#L136) from SQLite. Maybe it's a serdes, maybe it's an association. 

Based on what you've provided, that seems like an error that's coming from your UUID package, but I'm not sure.

**Comment by tshedor** [comment]
@devj3ns Thanks for formatting these in drawers. Makes it easier. 

What about your migration? What's the migration that was generated for `Project` or more specifically the migration that was generated for the addition of `id`? I'm wondering if the migration was generated incorrectly.

Also, for what it's worth, there may be a simpler way to do this:

```dart
Project({
  String? id
}) : this.id = id ?? const Uuid().v4()

@Sqlite(unique: true, index: true)
final String id;
```

**Comment by devj3ns** [comment]
Yeah, that's true, maybe I might just remove my UUID class and use the code snippet you provided.

For the change from `final String id;` to `final UUID id;` on the model there was no new migration generated.

<details>
<summary>That's the migration file</summary>

```
// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20240508065905_up = [
  InsertTable('Project'),
  InsertColumn('id', Column.varchar, onTable: 'Project', unique: true),
  InsertColumn('identifier', Column.varchar, onTable: 'Project', unique: true),
  InsertColumn('status', Column.integer, onTable: 'Project'),
  InsertColumn('building_address', Column.varchar, onTable: 'Project'),
  InsertColumn('building_city', Column.varchar, onTable: 'Project'),
  InsertColumn('building_zip_code', Column.integer, onTable: 'Project'),
  InsertColumn('client_first_name', Column.varchar, onTable: 'Project'),
  InsertColumn('client_last_name', Column.varchar, onTable: 'Project'),
  InsertColumn('client_company', Column.varchar, onTable: 'Project'),
  InsertColumn('client_email', Column.varchar, onTable: 'Project'),
  InsertColumn('client_phone', Column.varchar, onTable: 'Project'),
  InsertColumn('client_mobile_phone', Column.varchar, onTable: 'Project')
];

const List<MigrationCommand> _migration_20240508065905_down = [
  DropTable('Project'),
  DropColumn('id', onTable: 'Project'),
  DropColumn('identifier', onTable: 'Project'),
  DropColumn('status', onTable: 'Project'),
  DropColumn('building_address', onTable: 'Project'),
  DropColumn('building_city', onTable: 'Project'),
  DropColumn('building_zip_code', onTable: 'Project'),
  DropColumn('client_first_name', onTable: 'Project'),
  DropColumn('client_last_name', onTable: 'Project'),
  DropColumn('client_company', onTable: 'Project'),
  DropColumn('client_email', onTable: 'Project'),
  DropColumn('client_phone', onTable: 'Project'),
  DropColumn('client_mobile_phone', onTable: 'Project')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20240508065905',
  up: _migration_20240508065905_up,
  down: _migration_20240508065905_down,
)
class Migration20240508065905 extends Migration {
  const Migration20240508065905()
    : super(
        version: 20240508065905,
        up: _migration_20240508065905_up,
        down: _migration_20240508065905_down,
      );
}
```
</details>

**Comment by tshedor** [comment]
@devj3ns Sorry just want to followup on a few things. 

1. Did the UUID-as-serdes work? Please remove all annotations from the field in the model on any of the `UUID` fields except `@Sqlite(index: true, unique: true)`
2. Would you end up going the `final String id` route instead of doing the custom Serdes?

**Comment by devj3ns** [comment]
@tshedor I would like to use the `OfflineFirstSerdes`, but after some more testing, the adapter file is still not being generated when using the Serdes field.

I have created a minimal, reproducible example [here](https://github.com/devj3ns/brick_bug_reproduction).

**Comment by tshedor** [comment]
@devj3ns Thanks for creating that. With a small test and repository I was able to look at the stack trace.

```dart
// lib/brick/repository.dart
import 'package:brick_offline_first_with_rest/brick_offline_first_with_rest.dart';
import 'package:brick_rest/brick_rest.dart';
import 'package:brick_sqlite/brick_sqlite.dart';
import 'package:brick_test/brick/brick.g.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart' show databaseFactoryFfi;
import 'package:brick_test/brick/db/schema.g.dart';
export 'package:brick_core/query.dart' show And, Or, Query, QueryAction, Where, WherePhrase;

class Repository extends OfflineFirstWithRestRepository {
  Repository({required super.restProvider, required super.sqliteProvider})
      : super(
          migrations: migrations,
          offlineQueueManager: RestRequestSqliteCacheManager(
            'brick_offline_queue.sqlite',
            databaseFactory: databaseFactoryFfi,
          ),
        );
}

// test/widget_test.dart
import 'package:brick_offline_first_with_rest/testing.dart';
import 'package:brick_rest/brick_rest.dart';
import 'package:brick_sqlite/brick_sqlite.dart';
import 'package:brick_test/brick/brick.g.dart';
import 'package:brick_test/brick/models/project.model.dart';
import 'package:brick_test/brick/repository.dart';
import 'package:brick_test/brick/utils/uuid.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  sqfliteFfiInit();

  group("MySqliteProvider", () {
    late Repository repository;

    setUpAll(() async {
      repository = Repository(
        restProvider: RestProvider(
          'http://0.0.0.0:3000',
          modelDictionary: restModelDictionary,
          client: StubOfflineFirstWithRest(
            baseEndpoint: 'http://0.0.0.0:3000',
            responses: [
              StubOfflineFirstRestResponse('{"name":"Bob"', endpoint: 'users'),
            ],
          ).client,
        ),
        sqliteProvider: SqliteProvider(
          inMemoryDatabasePath,
          databaseFactory: databaseFactoryFfi,
          modelDictionary: sqliteModelDictionary,
        ),
      );

      await repository.initialize();
    });

    test('uuid insert', () async {
      await repository.upsert<Project>(Project(name: 'my-project', id: UUID('1234')));
    });
  });
}
``` 
This shows exactly where the error is coming from - `primaryKeyByUniqueColumns`. 

```dart
final results = await executor.rawQuery('''
        SELECT * FROM `Project` WHERE id = ? LIMIT 1''', [instance.id]);
```

The Brick architecture always assumed that uniquely identified fields would be single value - a string, an int, any sort of primitive - and never assumed the value would be more complex like a class. Architecturally, I'd still advise that you go the `final String id` route to avoid future maintainers from adding complexity within this class. 

However, this is something that Brick should at least natively support and perhaps discourage in the `@Sqlite(unique)` comments.

It's past my bedtime. This is a relatively quick fix that I will address this week.

**Comment by devj3ns** [comment]
Great, you found the root of the problem. A fix for this would be awesome, but no hurries👍

Thanks a lot for your time, I truly appreciate it!

**Comment by tshedor** [comment]
@devj3ns  This has been released in `brick_offline_first_build` 3.2.0. Please update your code to that version (and make sure dependency `brick_sqlite_generators` is upgraded to 3.1.0).

If the fix works, please close this issue

**Comment by devj3ns** [comment]
Hey @tshedor, thanks for working on this!

However, `brick_offline_first_build 3.2.0` is not available on [pub.dev](https://pub.dev/packages/brick_offline_first_build/changelog) and this feature was added to the 3.1.0 changelog.

**Comment by tshedor** [comment]
@devj3ns You're right. Please try _build 3.1.0.

**Comment by devj3ns** [comment]
@tshedor I just tested it and it works 🎉. Thank you, I appreciate it 👍
