### ISSUE TITLE
Question (Perhaps Not an Issue) About topLevelKey

### ISSUE THREAD

**Issue by SubutaDan** [GetDutchie/brick#385]
I noticed some magic which I am trying to understand.  The  API I am using returns the list of my objects as the contents of a named array:

```
{
 "items": [
  {
   "kokoId": "63ebb313-251d-40ad-bc0e-9693489b6a85",
   "kokoName": "klambake",
   "latitude": 457.0,
   "longitude": 22.0,
. . .
```

Somehow Brick seems to have figured this out and is accessing and de-serializing my objects successfully.  I looked at the Brick code and I though this must be the result the default topLevelKey behavior  in rest_provider.dart.  To try to confirm this theory I added a topLevelKey parameter to my RestRequest constructor invocation in my request transformer:
```
   return RestRequest(
        url: '/_ah/api/kokodokoapi/v1/kokos',
        topLevelKey: 'THERE_IS_NO_SUCH_KEY');
  }
```
but that didn't seem to affect the behavior. I tried both a key that didn't exist and a key that exists but isn't the correct topLevelKey.

Is it the topLevelKey feature that is making my code work?  

Can you explain how to use the topLevelKey feature correctly?

Thank you for your help.

**Comment by tshedor** [comment]
Hi @SubutaDan , the `topLevelKey` is only at the very, very top. There is a bit of magic indeed in [the decoding process](https://github.com/GetDutchie/brick/blob/main/packages/brick_rest/lib/src/rest_provider.dart#L178-L184):

```dart
if (key != null && decoded[key] != null) {
  return decoded[key];
} else if (decoded is Map) {
  if (decoded.keys.length == 1) {
    return decoded.values.first;
  }
}
```

> I tried both a key that didn't exist

Here, Brick determines that while a key is defined it does not exist. So it looks for a map in the response payload. Since it's `{items: itemsArray}` (a map with a length of 1), Brick chooses the first value of the first key and returns that.

> a key that exists but isn't the correct topLevelKey.

This is functionally similar to the first case.

> Is it the topLevelKey feature that is making my code work?

Yes and no. `topLevelKey` will make your code work if it's defined correctly, but it's also extremely permissive and forgiving.

**Comment by SubutaDan** [comment]
Amazing! Thanks.

-Dan

On 28 May 2024 04:32:24 GMT+09:00, Tim Shedor ***@***.***> wrote:
>Hi @SubutaDan , the `topLevelKey` is only at the very, very top. There is a bit of magic indeed in [the decoding process](https://github.com/GetDutchie/brick/blob/main/packages/brick_rest/lib/src/rest_provider.dart#L178-L184):
>
>```dart
>if (key != null && decoded[key] != null) {
>  return decoded[key];
>} else if (decoded is Map) {
>  if (decoded.keys.length == 1) {
>    return decoded.values.first;
>  }
>}
>```
>
>> I tried both a key that didn't exist
>
>Here, Brick determines that while a key is defined it does not exist. So it looks for a map in the response payload. Since it's `{items: itemsArray}` (a map with a length of 1), Brick chooses the first value of the first key and returns that.
>
>> a key that exists but isn't the correct topLevelKey.
>
>This is functionally similar to the first case.
>
>> Is it the topLevelKey feature that is making my code work?
>
>Yes and no. `topLevelKey` will make your code work if it's defined correctly, but it's also extremely permissive and forgiving.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GetDutchie/brick/issues/385#issuecomment-2133971088
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Japan: +81 70 911 52405
US: +1 704 380 9253
UK: +44 7875 599 430
