### ISSUE TITLE
Read from REST but Don't Write Back to REST

### ISSUE THREAD

**Issue by SubutaDan** [GetDutchie/brick#398]
I have what may be an unusual requirement.  I am using on offline-first-with-REST data source to populate a pick list.  It is working well.  Now I would like to be able to write items back to it, but only have them go to Sqlite and not to REST.  Is this possible?

I have a work-around in place, but it involves flushing and reloading the Brick provider frequently, so I would like to do better if I can.

Thanks very much.

**Comment by hortigado** [comment]
Hi can you try  for example   `Repository().sqliteProvider.upsert(AgeModel(weight: 12, created: DateTime.now()));`
I haven't tried it but it should work. Regards

**Comment by SubutaDan** [comment]
Thanks, @hortigado . That seems to be just what I was looking for.
-Dan

**Comment by tshedor** [comment]
Thank you @hortigado
