### ISSUE TITLE
Unexpected Remote Provider Calls for Associated Data

### ISSUE THREAD

**Issue by devj3ns** [GetDutchie/brick#399]
Hey 👋
I have a question regarding associations.

In my app, I have `Project`s and `Customer`s. Every project is associated with one customer. I just spotted that every time I fetch a project from the remote provider (in my case a REST API), brick tries to fetch the associated customer from the REST API, but fetches the wrong customer.

This is the customer field on the **`Project` model**:

```dart
@Rest(toGenerator: '%INSTANCE_PROPERTY%.id.value')
@Sqlite(index: true)
final Customer customer;
```

which generates the following code inside the `_$ProjectFromSqlite` method for the project adapter:

```dart
return Project(
  ...
  customer: (await repository!.getAssociation<Customer>(
          Query.where(
              'primaryKey', data['customer_Customer_brick_id'] as int,
              limit1: true),
        ))! .first,
  ...
);
```

I fetch a project from the remote provider using an `OfflineFirstWithRestRepository` named `DataRepository`:

```dart
await DataRepository().get<Project>(
      query: Query.where('id', "01a92e7e-fd16-4d1f-93be-ba50e0dd8efd"),
      policy: OfflineFirstGetPolicy.awaitRemote,
);
```

When running the above code with an empty local db, the following requests are sent to the REST API:

1. `.../projects?id=eq.01a92e7e-fd16-4d1f-93be-ba50e0dd8efd&select=*,customer:customers(*)` (This returns the correct project with the customer joined)
2. `.../customers?limit=1` (This returns one random customer because the `primaryKey` query, which contains Brick's local ID is unknown to the REST API

Why is the second request created and sent to the REST API? For fetching one customer, this is not big deal, but when fetching a list of projects, for each project a `.../customers?limit=1` request is sent which creates a lot of traffic. How can I avoid this?

One idea I have is adjusting the code to get the association inside the project adapter to only get the customer from the local db:

```dart
return Project(
  ...
  customer: (await repository!.get<Customer>(
        query: Query.where(
            'primaryKey', data['customer_Customer_brick_id'] as int,
            limit1: true),
        policy: OfflineFirstGetPolicy.localOnly,
      )).first,
  ...
);
```
This removes all these unnecessary `.../customers?limit=1` requests. Is this a recommended workaround, or does the problem lie elsewhere?

Thanks in advance 🙏

**Comment by hortigado** [comment]
Hi, this shouldn't happen, have you tried using `@OfflineFirst` because it is recommended for associations.
```
@OfflineFirst(where: {'id' : "data['customer']['id']"})
final Customer customer;
```

**Comment by tshedor** [comment]
@devj3ns This often happens because there are no local instances of `Customer`, and since you said your local is clear, this makes sense. The SQL that's generated is doing its best to find _any_ customer because `customer` is a non-nullable field on `Project`. 

@hortigado is right, `@OfflineFirst(where:` is what you need here to associate the `Customer` remote key (i.e. your primary key in your Supabase DB if you're still using Supabase) to the `Project` instance. That way, when you make a fresh request, the generated REST will include the proper mapping. 

The generated code would look something like this: 

```dart
  return Project(
      customer: await repository
          ?.getAssociation<Customer>(
              Query(where: [Where.exact('id', data['customer']['id'])], providerArgs: {'limit': 1}))
          .then((r) => r?.isNotEmpty ?? false ? r!.first : null), 
```

**Comment by devj3ns** [comment]
Thanks, @tshedor & @tshedor. 

Yes, this solves the problem with the wrong customer being fetched. Now, the REST request to the customer endpoint to get the projects associated customer includes its ID (e.g., `/customers?id=eq.56c4ba6d-8e2c-41e1-8382-6f977fdcd4b5&limit=1`).

**Comment by devj3ns** [comment]
I have a related question: For every REST request to the project endpoint, I am joining the customers' data, which means when fetching a project, the client also receives the associated customers' data. This means the extra REST request to fetch the associated customer is redundant. Currently, when I fetch a batch of say 20 projects, brick makes 20 REST calls to get the associated customers' data, which is not ideal.

I tried the following approach to improve this: 

1. I did **not** use the `@OfflineFirst(where: ...)` annotation. This means the `_$ProjectFromRest` method just uses the following code to transform the customer data:

```dart
customer: await CustomerAdapter().fromRest(data['customer'],
          provider: provider, repository: repository),
```
For me, using this makes sense because when we get the project data from the REST API, it already includes the customers data. So we do not need to make a REST call, opposed to using `getAssociation` here, which is used when adding the `@OfflineFirst(where: ...)` annotation.

2. I replaced the generated code for getting the customer inside `_$ProjectFromSqlite` from using `getAssociation` to the following:

```dart
customer: (await repository!.get<Customer>(
        query: Query.where('primaryKey', data['customer_Customer_brick_id'] as int, limit1: true),
        policy: OfflineFirstGetPolicy.localOnly,
      )).first,
```

This only gets the customer from the local database, instead of creating an extra REST request. At the time this is called, the customer is already present in the local database, so the REST request is not needed.

---

I tested the above approach with an empty local database, and it works, no more redundant requests to the customers REST endpoint. 

I guess it is not recommended to make such manual changes to the generated adapter files. @tshedor, how would you approach this?

**Comment by tshedor** [comment]
@devj3ns your original code contains this:

```dart
await DataRepository().get<Project>(
      query: Query.where('id', "01a92e7e-fd16-4d1f-93be-ba50e0dd8efd"),
      policy: OfflineFirstGetPolicy.awaitRemote,
);
```

If you don't need to make those fetches each time, change your policy to `OfflineFirstGetPolicy.awaitRemoteWhenNoneExist`.

**Comment by devj3ns** [comment]
Thanks for the quick reply @tshedor.

Unfortunately, since it's a multi-user app I have to use `awaitRemote` to make sure the data is fresh everytime a project is viewed.

**Comment by hortigado** [comment]
Hi, I haven't used Supabase for a long time, so I don't remember very well how it handles relationships. OfflineFirst is used when the server gives us a schema similar to this
```
{
"customers": [{
"id": 1,
"pizza_ids": [
1
],
"first_name": "Wallace",
"last_name": "Wallaceton"
}]
```
It only gives us the pizza ids, so it's correct to make another request with that id. If Supabase already gives us the pizza array, it doesn't make sense to use associations with brick. It's better to do everything with the state manager.

```
//ProjectModel
@Rest(ignore: true)
@Sqlite(ignore: true)
Customer customer,
//CustomerModel
List<Project> Projects;
//get customer function
Customer customer=DataRepository().get<Customer>(
query: Query.where('id', "01a92e7e-fd16-4d1f-93be-ba50e0")
policy: OfflineFirstGetPolicy.awaitRemote,
);
for(project in customer.projects){
project.customer=customer; // or they get the information from sqlite but I see it as unnecessary
}
```
In the case of getting the project from the rest first you can do something similar by making a request `awaitremotewhennotexist or awaitremote` from the client 
I'm using my cell phone so there may be errors in the code

**Comment by tshedor** [comment]
@devj3ns i think this might be the limit of the Supabase-as-REST API. To optimize against the duplicate requests it needs a proper provider implementation. While I wouldn't recommend this to most, you're an advanced user and know the cost of modifying generated adapter code. So if you do modify the generated adapter, maybe you can automate the swap with a Dart or sed shell script so that your other teammates (?) dont mistakenly overwrite adapter code on subsequent generations. 

For the function you referenced, I think you want the .alwaysHydrate policy. That returns local and then backgrounds the remote fetch. Couple that with the repository's #subscribe method and you should get your local updates and then your remote results would render when they arrive.

**Comment by devj3ns** [comment]
Okay, thanks @tshedor. Then I will explore modifying the adapter code properly. Maybe I can use the model annotations to pass the adapter code for the `fromSqlite` and `fromRest` method. If that does not work I will try using a script as you suggested. 

I do not use the `alwaysHydrate` policy because my UI displays the current loading state and data source. That's why I created a function that returns a Stream combining the data with it's source (local/remote) and fetch status. This allows me to inform the user whether they're viewing local data or fresh data from the remote source, while also displaying a small loading spinner when data is being fetched remotely.
