### ISSUE TITLE
bug(supabase-integration): Supabase query includes join even though there is no associationForeignKey defined

### ISSUE THREAD

**Issue by devj3ns** [GetDutchie/brick#425]
I have a `BuildingWindows` model which has the following field:

```dart
@Supabase(foreignKey: null)
final List<WindowType>? windowTypes;
```

Because this is stored as a JSONB field in the Supabase DB (to simplify the sync), it does not specify a `foreignKey` because there is no remote `WindowType` table.

Even though the `foreignKey` is null, the REST Request includes a join inside the select clause, which should not be the case in my opinion. Because of the invalid join, the Postgrest API throws the following exception:

```
PostgrestException(
     message: "failed to parse select parameter (id,project_id,window_types(id,glazing,frame_material,manufacturing_year,locations),notes)", 
     code: PGRST100, 
     details: unexpected "(" expecting ":" or field name (* or [a..z0..9_$]), 
     hint: null)
```

---
Moreover, I noticed, that the `associationForeignKey` field inside the adapter is `associationForeignKey: 'null'` instead of  `associationForeignKey: null` when no `associationForeignKey` was provided in the model field  `@Supabase` annotation.

**Comment by devj3ns** [comment]
@tshedor, `WindowType` is a model:

```dart
@ConnectOfflineFirstWithSupabase()
class WindowType extends OfflineFirstWithSupabaseModel {
  WindowType({
    required this.id,
    required this.glazing,
    required this.frameMaterial,
    required this.manufacturingYear,
    required this.locations,
  });

  @Sqlite(unique: true, index: true)
  @Supabase(unique: true)
  final UUID id;

  @Sqlite(enumAsString: true, nullable: true)
  @Supabase(enumAsString: true, nullable: true)
  final WindowGlazing? glazing;

  @Sqlite(enumAsString: true, nullable: true)
  @Supabase(enumAsString: true, nullable: true)
  final WindowFrameMaterial? frameMaterial;

  final int? manufacturingYear;

  final String? locations;
}
```

**Comment by tshedor** [comment]
If it's a model, shouldn't it have a database table equivalent? Otherwise it should be a serdes if it's only JSONB in Supabase

**Comment by devj3ns** [comment]
Yes, you are totally right. I will change that.
