### ISSUE TITLE
Issue upserting SupabaseModel with association

### ISSUE THREAD

**Issue by devj3ns** [GetDutchie/brick#431]
In my project, I have a model Project and a model Customer:

```dart
@ConnectOfflineFirstWithSupabase( supabaseConfig: SupabaseSerializable(tableName: 'projects'))
class Project extends OfflineFirstWithSupabaseModel {

  ...
  
  @Supabase(foreignKey: 'customer')
  @Sqlite(index: true)
  final Customer customer;
}
```

```dart
@ConnectOfflineFirstWithSupabase( supabaseConfig: SupabaseSerializable(tableName: 'customers'))
class Customer extends OfflineFirstWithSupabaseModel {

  ...
  
  @Sqlite(unique: true, index: true)
  @Supabase(unique: true)
  final UUID id;
}
```

When upserting a Project, the following exception is thrown:

```
type 'Project' is not a subtype of type 'Customer' of 'input' #0      CustomerAdapter.toSupabase (package:tragwerk_app/brick/adapters/customer_adapter.g.dart:344:52)
#1      SupabaseProvider._upsertByType (package:brick_supabase/src/supabase_provider.dart:107:34)
#2      SupabaseProvider._recursiveAssociationUpsert (package:brick_supabase/src/supabase_provider.dart:149:18)
#3      SupabaseProvider._recursiveAssociationUpsert (package:brick_supabase/src/supabase_provider.dart:142:13)
#4      SupabaseProvider.upsert (package:brick_supabase/src/supabase_provider.dart:90:18)
#5      OfflineFirstRepository.upsert (package:brick_offline_first/src/offline_first_repository.dart:404:28)
<asynchronous suspension>
```

I checked the debugger and the issue is inside the `_recursiveAssociationUpsert` method. 

When it is first called from the `upsert` method, the instance is the project data and the type is `Project`, which is correct. But when the associations are iterated over in the for loop, the `_recursiveAssociationUpsert` is called again, but this time with the type of `Customer` which is also correct, but the instance is the project data instead of the nested customer data. This means that the `_upsertByType` method is called with the project data but the `Customer` type. For that reason, the exception is thrown inside the `toSupabase` method, as the project data is passed instead of the customer data.

I guess the fix should be to pass the associated field of the model instead of the original model here: https://github.com/GetDutchie/brick/blob/fe6c1d78285399662936b7180be7dc03d7ecebc4/packages/brick_supabase/lib/src/supabase_provider.dart#L143

**Comment by tshedor** [comment]
Great investigation work. Unfortunately, dynamic properties can't be invoked in strong Dart land, so I think the best way to handle this is to convert everything to a map first and then process it. I've made some changes and published the fixes for `brick_supabase_generators` and `brick_supabase` in #430

**Comment by devj3ns** [comment]
Great fix, upserting the` Project` now works :)
