### ISSUE TITLE
[Supabase integration]: Null check exception thrown in PostgrestBuilder when upserting while being offline

### ISSUE THREAD

**Issue by devj3ns** [GetDutchie/brick#439]
This morning, I tested if the app I am migrating to the new Supabase integration still works offline. Unfortunately, when I upsert a model while being offline, the following exception is thrown:

```
Null check operator used on a null value
#0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:254:27)
#1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:164:14)
<asynchronous suspension>
#2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:372:24)
<asynchronous suspension>
```

I checked the debugger, and the exception is thrown in [this line](https://github.com/GetDutchie/brick/blob/99f7b253063be6765f7e6f852f84e75dcc876836/packages/brick_supabase/lib/src/supabase_provider.dart#L122) inside the `_upsertByType` function of the `SupabaseProvider`:

`final resp = await builder.select(queryTransformer.selectFields).limit(1).maybeSingle();`

I can also reproduce this issue with the [example_supbase](https://github.com/GetDutchie/brick/tree/supabase-integration/example_supabase) flutter app. (For that, I added a button which upserts a new customer because currently the example only displays the customers but does not allow adding a new one).

**Comment by tshedor** [comment]
@devj3ns Good catch; fixed and merged in #436 . I haven't published this.

**Comment by devj3ns** [comment]
@tshedor, thanks! I'll do some more tests on Monday and report back if there are any other issues or bugs.

**Comment by devj3ns** [comment]
I just tested it and the exception is gone now.
