### ISSUE TITLE
Supabase: PostgrestException thrown when fetching data while being offline

### ISSUE THREAD

**Issue by devj3ns** [GetDutchie/brick#441]
When using the Supabase integration and fetching data using `get` or `getBatched` while being offline, the following error is thrown:

```
Unhandled Exception: PostgrestException(message: unknown internal error, code: 501, details: null, hint: null)
E/flutter ( 1960): #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:283:7)
E/flutter ( 1960): #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:164:14)
E/flutter ( 1960): <asynchronous suspension>
E/flutter ( 1960): #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:372:24)
E/flutter ( 1960): <asynchronous suspension>
```

In contrast, the REST integration returns an empty array in the same case. I took a look at the code, and it appears that the `OfflineFirstWithSupabaseRepository` is not overriding the `get` method, like the `OfflineFirstWithRestRepository` is.

When comparing the [`OfflineFirstWithRestRepository`](https://github.com/GetDutchie/brick/blob/dfc0d225ef6da8847e9aa495aadc808f47f461a3/packages/brick_offline_first_with_rest/lib/src/offline_first_with_rest_repository.dart) and the [`OfflineFirstWithSupabaseRepository`](https://github.com/GetDutchie/brick/blob/66b9c4b52f30b4962ff7a6573c668fd882d1f557/packages/brick_offline_first_with_supabase/lib/src/offline_first_with_supabase_repository.dart), I noticed that the `delete` and `hydrate` methods are also not overridden in the Supabase Repository to catch specific exceptions.

**Comment by devj3ns** [comment]
I just saw that there is another discrepancy: when upserting using the `requireRemote` policy and forcing an exception (e.g., Postgres Unique Constraint Violation), the original exception is thrown inside a `OfflineFirstException` for the REST repository, but inside a `Exception` inside an `OfflineFirstException` for the Supabase repository. I think this should be aligned.

**Comment by tshedor** [comment]
@devj3ns Aligned how? What's the ideal state?

**Comment by devj3ns** [comment]
In my opinion, the ideal situation would be that bricks REST and Supabase integration treat exceptions similarly or equally.

**Comment by tshedor** [comment]
Merged not published
