### ISSUE TITLE
How do I subscribe to specific data

### ISSUE THREAD

**Issue by ForterLi** [GetDutchie/brick#456]
Multi-user program, only subscribe to update the current user data

**Comment by tshedor** [comment]
@ForterLi You can use the `subscribe` [method on the repository](https://getdutchie.github.io/brick/#/introduction/usage?id=fetching-data) with a query. This will give you a `Stream` that you can listen to.

```dart
final usersStream = Repository().subscribe<User>(query: Query.where('name', 'Thomas'));
```

**Comment by ForterLi** [comment]
> @ForterLi您可以`subscribe` [在存储库上使用该方法](https://getdutchie.github.io/brick/#/introduction/usage?id=fetching-data)并进行查询。这将为您提供一个`Stream`您可以收听的内容。
> 
> ```dart
> final usersStream = Repository().subscribe<User>(query: Query.where('name', 'Thomas'));
> ```

**Comment by ForterLi** [comment]
Whether the local database synchronizes all the remote data, or whether it can selectively synchronize the data it needs

**Comment by tshedor** [comment]
@ForterLi The local database only caches what you've requested from `.get` requests (sometimes it will always get new data, sometimes it will only get missing data based on [what policy is used](https://getdutchie.github.io/brick/#/offline_first/policies)). The local database does not automatically sync with the remote database. `#subscribe` is only reactive to updates made to the local database.
