### ISSUE TITLE
Models With Freezed?

### ISSUE THREAD

**Issue by jtkeyva** [GetDutchie/brick#458]
i use freezed for my models. should i not with brick?
should i have 2 separate models files? probably not...?

now brick wants to generate models too. have do we deal with camelCase to snake_case conversion with brick?

thanks

```import 'package:freezed_annotation/freezed_annotation.dart';

part 'contact_model.freezed.dart';
part 'contact_model.g.dart';

@freezed
class Contact with _$Contact {
  const factory Contact({
    @JsonKey(name: 'contact_id') @Default('') String contactId,
    @JsonKey(name: 'created_at', defaultValue: null, includeIfNull: false)
    final DateTime? createdAt,
    @JsonKey(name: 'updated_at', defaultValue: null, includeIfNull: false)
    final DateTime? updatedAt,
    @JsonKey(name: 'created_by') @Default('') String createdBy,
    @JsonKey(name: 'place_id') String? placeId,
    @JsonKey(name: 'type') String? type,
    @JsonKey(name: 'title') String? title,
    @JsonKey(name: 'first_name') String? firstName,
    @JsonKey(name: 'last_name') String? lastName,
    @JsonKey(name: 'email') String? email,
    @JsonKey(name: 'phone') String? phone,
    @JsonKey(name: 'mobile_phone') String? mobilePhone,
    @JsonKey(name: 'note') String? note,
    @JsonKey(name: 'photo_url') String? photoUrl,
    @JsonKey(name: 'links') String? links,
    @JsonKey(name: 'connections') String? connections,
    @JsonKey(name: 'website') String? website,
    @JsonKey(name: 'referred_by') String? referredBy,
  }) = _Contact;

  factory Contact.fromJson(Map<String, dynamic> json) =>
      _$ContactFromJson(json);
}
```

**Comment by tshedor** [comment]
@jtkeyva Unfortunately, `freezed` is incompatible with Brick. The way freezed generates the models doesn't allow Brick to infer the fields.

> should i have 2 separate models files? probably not...?

Theoretically, you could have a mixin with non-final fields (e.g. computed getters and setters), but I can't guarantee that this will work. You can try it, but if it doesn't work then the final answer is one file.

> now brick wants to generate models too. have do we deal with camelCase to snake_case conversion with brick?

Depending on your remote provider (assuming it's Supabase based on your past issues), you can use the `FieldRename` [configuration on your model's annotation](https://getdutchie.github.io/brick/#/supabase/models?id=supabaseserializablefieldrename).

**Comment by jtkeyva** [comment]
Ok got it thanks. Well I am considering going all in on Brick so now I have to refactor how I do models. I like freezed because it is airtight and has a lot of nice conveniences. 

how about https://pub.dev/packages/dart_mappable? that generates code too though.

Any other suggestions? How do you write your models? CopyWith? Equatable?

**Comment by tshedor** [comment]
@jtkeyva I would largely say that code generators don't interact with other code generators, and Brick generates its own code. 

I don't like using an `Equatable` generator because often I have a unique property (like a `uuid`) that is sufficient for the `=> props` getter. Generators will add all fields, which could throw false positives (such as you change the name of a user in a list, and now two users are present because they have the same UUID but differing names). So even if I'm in an app using an equatable generator, I typically have to overwrite the generated output.

For `copyWith`, I generally write these by hand because I don't want all fields to be mutable (for example again, `uuid` should never be changed by a `copyWith`). However, a `copyWith` can be generated and applied as a mixin where necessary. Brick has played nice with the [copy_with_extension_gen](https://pub.dev/packages/copy_with_extension_gen) package.

**Comment by jtkeyva** [comment]
awesome thanks! so excuse me for asking too much...i'm having a hard time with this. as  freezed is super simple and chat-gpt isn't hip to brick yet.

i usually ask it to make a freezed model from my table definition. is there possiblity of a such for brick? all i need is one solid example and i can use that as a template. any help appreciated

```create table
  public.business (
    business_id uuid not null default extensions.uuid_generate_v4 (),
    name text not null,
    website text null,
    note text null,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    industry uuid null,
    business_type uuid null,
    address text null,
    address_2 text null,
    city text null,
    state text null,
    zip text null,
    referred_by text null,
    handwriting text null,
    qr_code text null,
    video_tour_url text null,
    showcase_video_url text null,
    referred_by_contact_id uuid null,
    constraint business_pkey primary key (business_id),
    constraint business_name_unique unique (name),
    constraint business_business_type_fkey foreign key (business_type) references business_type (business_type_id),
    constraint business_industry_fkey foreign key (industry) references industry (industry_id),
    constraint business_referred_by_contact_id_fkey foreign key (referred_by_contact_id) references contact (contact_id)
  ) tablespace pg_default;```

**Comment by tshedor** [comment]
Paste the schema after this prompt:
```
I'm converting a SQL schema to Dart. I'm going to give you the SQL schema. You will return a Dart class with final fields for every SQL column. The Dart class should translate SQL column types to Dart native types. For example, given `name text null`, the Dart field would be `final String? name;`. The Dart class must also include a constructor with named arguments.
```

**Comment by jtkeyva** [comment]
thank you!

this seem ok? isn't supabase snake_case? or is pascal case similar?

```// lib/models/business_model.dart

import 'package:brick_core/field_rename.dart';
import 'package:brick_offline_first_with_supabase/brick_offline_first_with_supabase.dart';
import 'package:brick_sqlite/brick_sqlite.dart';
import 'package:brick_supabase/brick_supabase.dart';
import 'package:uuid/uuid.dart';

// Your model definition can live anywhere in lib/**/* as long as it has the .model.dart suffix
// Assume this file is saved at my_app/lib/src/users/user.model.dart

import 'package:brick_offline_first_with_supabase/brick_offline_first_with_supabase.dart';
import 'package:brick_sqlite/brick_sqlite.dart';
import 'package:brick_supabase/brick_supabase.dart';
import 'package:uuid/uuid.dart';

@ConnectOfflineFirstWithSupabase(
  supabaseConfig: SupabaseSerializable(tableName: 'business'),
)
@SupabaseSerializable(fieldRename: FieldRename.pascal)
class Business extends OfflineFirstWithSupabaseModel {
  // Be sure to specify an index that **is not** auto incremented in your table.
  // An offline-first strategy requires distributed clients to create
  // indexes without fear of collision.
  @Supabase(unique: true)
  @Sqlite(index: true, unique: true)
  final String businessId; // UUID is treated as a String in Dart
  final String name;
  final String? website;
  final String? note;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final String? industry; // UUID is treated as a String in Dart
  final String? businessType; // UUID is treated as a String in Dart
  final String? address;
  final String? address2;
  final String? city;
  final String? state;
  final String? zip;
  final String? referredBy;
  final String? handwriting;
  final String? qrCode;
  final String? videoTourUrl;
  final String? showcaseVideoUrl;
  final String? referredByBusinessId; // UUID is treated as a String in Dart

  Business({
    String? businessId,
    required this.name,
    this.website,
    this.note,
    this.createdAt,
    this.updatedAt,
    this.industry,
    this.businessType,
    this.address,
    this.address2,
    this.city,
    this.state,
    this.zip,
    this.referredByBusinessId,
  }) : this.businessId = businessId ?? const Uuid().v4();
}
```

**Comment by tshedor** [comment]
> this seem ok? isn't supabase snake_case? or is pascal case similar?

SQL convention is to snake case your columns. You're renaming based on how your Supabase table columns are configured.
