### ISSUE TITLE
SupaDart Package Generation (automatic model generation)?

### ISSUE THREAD

**Issue by jtkeyva** [GetDutchie/brick#459]
Would be pretty slick if we could use this to automatically create offline models:

https://pub.dev/packages/supadart

Would save time and eliminate typo's

**Comment by tshedor** [comment]
@jtkeyva yep, that looks pretty cool. This comes with its own querying superset, so it's not the right fit for Brick, but it is a good tool for people to use to create their first models.

**Comment by jtkeyva** [comment]
yeah i was thinking it could almost fully automate everything if put together just right

**Comment by bookshiyi** [comment]
Cool! I am also contributor of supadart.
But recently when I was about to use brick, I had to remove supadart.
I also expect brick to integrate the functions of supadart.

**Comment by tshedor** [comment]
PRs are open
