### ISSUE TITLE
[Help Request] Making sense of HttpClient behavior with Supabase/OfflineQueueHttpClient

### ISSUE THREAD

**Issue by edziegle** [GetDutchie/brick#464]
I am brand new to Flutter/Dart, and was actually inspired to try it out via the lovely tutorial on the [Supabase Blog](https://supabase.com/blog/offline-first-flutter-apps). At first I did not bother to put in my Supabase anonkey/url as I was more interested in checking out Brick, so I left the two as `supabaseUrl` and `supabaseAnonKey` in the repository initialization step.

But now what I am seeing after actually plugging the real variables in (via env var), is the built app seems to still be using the placeholders, for example an error from the http client:
```I/flutter ( 4780): OfflineQueueHttpClient#brick_offline_queue.sqlite: WARNING: #send: Invalid argument(s): No host specified in URI supabaseUrl/rest/v1/<snip>```

Likewise I see `"Authorization":"Bearer supabaseAnonKey","apikey":"supabaseAnonKey"` in the log messages. At first I suspected this was a build cache problem of some kind, so I ran `flutter clean` and reran the dart build runner, but with no success. I'm hoping I missed something simple; can you offer any guidance?

**Comment by tshedor** [comment]
@edziegle I'd recommend deleting the database. You can do this by deleting the application and all application data directly from your device. Or you can invoke `Repository().reset()` anywhere (like in `void main()`). Run this once, then delete the line, otherwise you won't persist any data between app starts.

**Comment by edziegle** [comment]
That did the trick! Thank you for taking time out of your day to help this Flutter noob :)

I'd also like to say, this tool you've built is excellent, keep up the great work!
