### ISSUE TITLE
Many to many joins or general workaround

### ISSUE THREAD

**Issue by nyejon** [GetDutchie/brick#482]
HI, I see in the documentation that many to many associations are not supported.

Does this mean that even if the intermediate join tables are manually defined that it will not work?

Also what does this mean?

[Unsupported Field Types](https://getdutchie.github.io/brick/#/supabase/fields?id=unsupported-field-types)
The following are not serialized to Supabase. **However, unsupported types can still be accessed in the model as non-final fields.**

Nested List<> e.g. <List<List<int>>>
Many-to-many associations

Is there any general workaround to get many to many joins to work manually?

**Comment by nyejon** [comment]
Hi @tshedor, thanks for the helpful input as always!

So if I would want to just go one way, without needing to go the other way through the relationships, I could do something like this? 

```dart
class Parent extends OfflineFirstWithSupabaseModel {
  final String parentId;
  final List<ParentChild> parentChildren;
}

class ParentChild extends OfflineFirstWithSupabaseModel {
  final String id;
  final Parent parent;
  final Child child;
}

class Child extends OfflineFirstWithSupabaseModel {
  final String childId;
  // Would this break things? I'll test it out later when I get the chance
  // final List<ParentChild> childParents
}
```

Basically, I would just like to access the properties of the parent's children from the Parent and would never go from the Child back to the Parent when I am populating from the parent point of view.

**Comment by tshedor** [comment]
> So only the first level of the parent, and not the full parent object will be populated when hydrating down?

That's correct, although I'd again caution you to avoid this pattern as it's fairly advanced and I won't be adding much more support for it. 

Regarding your code:

```dart
class Parent extends OfflineFirstWithSupabaseModel {
  final String parentId;
  final List<ParentChild> parentChildren;
}

class ParentChild extends OfflineFirstWithSupabaseModel {
  final String id;
  // This will be an infinite association
  final Parent parent;
  // This will not be
  final Child child;
}

class Child extends OfflineFirstWithSupabaseModel {
  final String childId;
}
```

So instead consider this pattern:

```dart
class Parent extends OfflineFirstWithSupabaseModel {
  final String parentId;
  final List<ParentChild> parentChildren;
}

class ParentChild extends OfflineFirstWithSupabaseModel {
  final String id;
  final Child child;
}

class Child extends OfflineFirstWithSupabaseModel {
  final String childId;
}
```

This way, your data flow is in a single direction - given the name `ParentChild`, you're probably only accessing these models when you already have a `Parent`.

**Comment by nyejon** [comment]
Thanks @tshedor, this seems to be working as expected!
