### ISSUE TITLE
Feature Request, toJson() and fromJson()

### ISSUE THREAD

**Issue by richard457** [GetDutchie/brick#488]
In working with pulling data from other sources e.g migrating from another DB or REST API, you find yourself writing a lot of boilerplates, it would be nice to have toJson() and fromJson() methods generated and exposed, this would allow users to work with API and migrations efficiently.

**Comment by tshedor** [comment]
Hey @richard457 , the idea of Brick is that you don't manage serialization and deserialization as that's handled implicitly by the adapters. Brick will not interpret model-level serialization/deserialization. 

If you need to store complex objects as strings, you can use an `OfflineFirstSerdes`. Enhanced enums can also be serialized by adding a  `fromJson` factory and a `toJson` method.

**Comment by richard457** [comment]
I understand it is nice to have.

**Comment by tshedor** [comment]
I would recommend using JsonSerializable if it's necessary
