### ISSUE TITLE
[Windows] Unable to open database on windows in release mode but worked in debug

### ISSUE THREAD

**Issue by richard457** [GetDutchie/brick#490]
SqfliteFfiException: SqfliteFfiException(sqlite_error: 14, , open_failed: SqliteException(14): while opening the database, unable to open database file, unable to open database file (code 14)}) DatabaseException(open_failed: SqliteException(14): while opening the database, unable to open database file, unable to open database file (code 14))
my repository
```dart
class Repository extends OfflineFirstWithSupabaseRepository {
  static late Repository? _singleton;

  Repository._({
    required super.supabaseProvider,
    required super.sqliteProvider,
    required super.migrations,
    required super.offlineRequestQueue,
    super.memoryCacheProvider,
  });

  factory Repository() => _singleton!;

  static Future<void> initializeSupabaseAndConfigure({
    required String supabaseUrl,
    required String supabaseAnonKey,
  }) async {
    final (client, queue) = OfflineFirstWithSupabaseRepository.clientQueue(
      databaseFactory:
          (Platform.isWindows) ? databaseFactoryFfi : databaseFactory,
    );
    final directory = Platform.isWindows
        ? (await getApplicationSupportDirectory()).path
        : await getDatabasesPath();

    final supabase = await Supabase.initialize(
      url: supabaseUrl,
      anonKey: supabaseAnonKey,
      httpClient: client,
    );

    final provider = SupabaseProvider(
      supabase.client,
      modelDictionary: supabaseModelDictionary,
    );

    _singleton = Repository._(
      supabaseProvider: provider,
      sqliteProvider: SqliteProvider(
        join(directory, "dbname"),
        databaseFactory:
            (Platform.isWindows) ? databaseFactoryFfi : databaseFactory,
        modelDictionary: sqliteModelDictionary,
      ),
      migrations: migrations,
      offlineRequestQueue: queue,
      memoryCacheProvider: MemoryCacheProvider(),
    );
  }
}
```

**Comment by tshedor** [comment]
Hi @richard457 this looks like a SQFlite error. I'd recommend you read through the SQFlite documentation or issues to find a solution.

**Comment by hortigado** [comment]
Print the directory and search your PC to see if the directory exists. The error usually means that the directory does not exist. I guess it is because the SupabaseProvider is not passing the path to Windows.

**Comment by hortigado** [comment]
Hi, The error usually means that the directory does not exist. Although I suppose it is because the path for windows is not being passed in the SupabaseProvider. So I think the supabase provider is not compatible with windows.
I just analyzed and it is correct, the path is created by default and is not compatible with windows. 
The solution is simple to create a variable databaseName as it is in Rest.  @tshedor You should review it for a pull request, thanks.

![image](https://github.com/user-attachments/assets/d6ad974c-7ab8-40f9-bc2d-67ce4a9e127c)

**Comment by richard457** [comment]
This is a blocker on windows for us, would appreciate your support.

**Comment by tshedor** [comment]
@richard457 @hortigado @lyhamissi this is available in `brick_offline_first_with_supabase` version 1.1.2
