### ISSUE TITLE
Can we provide a get interface for stream to implement a better user experience?

### ISSUE THREAD

**Issue by bookshiyi** [GetDutchie/brick#491]
Hi, 
Brick is an elegant method of offline-first app for me, it is so great!

I have seen a question whether brick provides a stream way to get data, or plan in the future?

Feature description:
> When developers call such an interface, brick first query the local data and return the data through the stream interface for display at the UI layer (which may not be accurate).Then start to fetch the remote data, and return it again through the stream interface when the remote data is successfully retrieved.

I have seen similar designs on many popular apps, which can ensure the loading speed (local data) and accuracy (remote data) of data at the same time.

Maybe we could understand(stream): Offline first, then? Remote second.

```dart
Stream<UserProfile> getUserProfile() async* {
  // Fetch the user profile from the database
  final userProfile = await _databaseService.fetchUserProfile();
  // Returns the database result if it exists
  if (userProfile != null) {
    yield userProfile;
  }

  // Fetch the user profile from the API
  try {
    final apiUserProfile = await _apiClientService.getUserProfile();
    //Update the database with the API result
    await _databaseService.updateUserProfile(apiUserProfile);
    // Return the API result
    yield apiUserProfile;
  } catch (e) {
    // Handle the error
  }
}
``` 

Reference document: https://docs.flutter.dev/cookbook/architecture/offline-first#using-a-stream

**Comment by tshedor** [comment]
Hi @bookshiyi good news - this [feature already exists](https://getdutchie.github.io/brick/#/introduction/usage?id=fetching-data) as `subscribe` on the Repository:

```dart
final users = repository.subscribe<User>().listen((users) {})
```

**Comment by bookshiyi** [comment]
Hi @tshedor 

ohhhh, thanks!
