### ISSUE TITLE
Help with foreignKey relation models

### ISSUE THREAD

**Issue by rlee1990** [GetDutchie/brick#493]
I am having a hard time creating a models for my supabase tables.
I have a user table a social_info table and a profile_photo table.
The social and profile tables both have a column called user_id that links to the user table at id.
I tried to create a user model with both other tables as child models and received errors.
I tried just making the user table a child of the other tables but keep receiving the below error
```The setter 'primaryKey' isn't defined for the type 'SocialInfoBrick'.
Try importing the library that defines 'primaryKey', correcting the name to the name of an existing setter, or defining a setter or field named 'primaryKey'.```.
Each table has an id column that is added to the model like so:
```
@Supabase(unique: true)
  @Sqlite(index: true, unique: true)
  final String id;
  ```
This is the foreignkey part:
```@Supabase(foreignKey: 'user_id')
  final UserBrick user;```

**Comment by tshedor** [comment]
@rlee1990 are you able to use the `profile_photo` and `social_info` as child tables of `User` instead? I think that will make more sense from a data flow perspective.

As far as the error you're experiencing, that isn't an error message I've written. What is the invocation that leads to that message?

**Comment by sgbeal** [comment]
Trivia: every time some types `@sqlite` _outside of a code block_ in github tickets, all members of the sqlite team get an email. The same probably applies to the supabase devs.

**Comment by rlee1990** [comment]
@tshedor In supabase there are children of the user table. The issue I think is when I add the as a child of the user model it gives me an error
```The named parameter 'socialInfo' is required, but there's no corresponding argument.
Try adding the required argument.```

here is the user model:
```
@ConnectOfflineFirstWithSupabase(
  supabaseConfig: SupabaseSerializable(tableName: 'user'),
)
class UserBrick extends OfflineFirstWithSupabaseModel {
  final String? bannedReason;
  final String createdAt;
  final String updatedAt;
  final bool isVerified;
  final bool subcribed;
  final bool didTutorial;
  final bool accountBanned;
  final String? bannedUntil;
  @Supabase(unique: true)
  @Sqlite(index: true, unique: true)
  final String id;

  @Supabase(foreignKey: 'user_id')
  final SocialInfoBrick socialInfo;

  UserBrick({
    this.bannedReason,
    required this.createdAt,
    required this.updatedAt,
    required this.isVerified,
    required this.subcribed,
    required this.didTutorial,
    required this.accountBanned,
    this.bannedUntil,
    required this.socialInfo,
    String? id,
  }) : id = id ?? const Uuid().v4();
}
```

**Comment by rlee1990** [comment]
> Trivia: every time some types `@sqlite` _outside of a code block_ in github tickets, all members of the sqlite team get an email (🙋). The same probably applies to the supabase devs.

Sorry

**Comment by sgbeal** [comment]
> Sorry

It's not your fault, just an unfortunate side-effect of npm package naming :/.

**Comment by tshedor** [comment]
> The issue I think is when I add the as a child of the user model it gives me an error

What do you mean "when you add"? You add the associations and then run build runner? 

> Try adding the required argument. here is the user model:

What is the full stack trace of this error? This isn't coming from Brick.

**Comment by rlee1990** [comment]
So thats the error I get in the adapter after I run build runner. 
Would this be the association? If not I am completely lost then.
```@Supabase(foreignKey: 'user_id')```

**Comment by tshedor** [comment]
> So thats the error I get in the adapter after I run build runner.

Can you please provide the full stack trace and the relevant lines in the adapter?

> Would this be the association? If not I am completely lost then.

Yes, however, you shouldn't need to specify this. Supabase will figure out how to pull the right table as long as you have foreign keys configured in the Supabase table. I think you'd be better off without specifying this property.

Lastly, can you confirm that `SocialInfoBrick` is a Brick model?

**Comment by rlee1990** [comment]
I got it working thank you there was a typo in OfflineFirstWithSupabaseModel for the SocialInfoBrick that vscode was not catching and now the adapter does not have an error. thank you.

**Comment by rlee1990** [comment]
Hey @tshedor sorry to bug you more on this. So I thought this would work but once I finally tried to run the app I get the below error:
```flutter: OfflineFirstRepository: WARNING: #hydrate supabase failure: PostgrestException(message: column social_info_1.web_site does not exist, code: 42703, details: Bad Request, hint: Perhaps you meant to reference the column "social_info_1.website".) ```
I suspect that the issue is that user table does not have a reference to the social_info table. The social_info table does hold a reference to user table. Is there a way around that to have the social_info under the user model?

**Comment by hortigado** [comment]
@rlee1990 hi, In your migration files is there a command to insert column social_info_1.website?

**Comment by rlee1990** [comment]
@hortigado no but this wasn't for an insert this is for a get and realtime request. The table is social_info no column in supabase with that name.

**Comment by tshedor** [comment]
@rlee1990 the casing of your field is incorrect or you need to specify the right Supabase column. It should be `final String website` or 
```dart
@Supabase(name: 'website')
final String webSite;
```

**Comment by rlee1990** [comment]
Oh I will give that a try

**Comment by rlee1990** [comment]
Thanks that worked.

**Comment by richard457** [comment]
A quick question when defining model
this: ```dart
class Photo extends OfflineFirstWithSupabaseModel {
  @Sqlite(unique: true, index: true)
  @Supabase(unique: true)
  final int id;


  @Supabase(foreignKey: 'user_id', )
  User user;

  @Sqlite(ignore: true)
  int get userId => user.id;
```
on supabase side do we have to have Photo table have user field as jsonb? and userId field as well? cc @rlee1990 @tshedor  I am asking because I tried without defining the field user in Photo table in supabase and I am getting  Failed assertion: line 217 pos 12: 'modelDictionary.adapterFor.containsKey(type)': Map<dynamic, dynamic> not found in the model dictionary #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)

**Comment by rlee1990** [comment]
@richard457 How most of mine are set up is that on one of the tables I have a link to the other table and in flutter I name the field after that column name or add the supabase notation with the foreign key set to the column name.

**Comment by richard457** [comment]
I think I have done the same but I keep getting  Failed assertion: line 217 pos 12: 'modelDictionary.adapterFor.containsKey(type)': Map<dynamic, dynamic> not found in the model dictionary
flutter @rlee1990 anything I need to supabase side?

**Comment by rlee1990** [comment]
@richard457 I would open a new issue and see if the owner can help. I'm still feeling my way through the packages also.

**Comment by richard457** [comment]
Thank you very much, I think relationship are not well covered in docs, I am struggling for the whole day.

**Comment by tshedor** [comment]
Yeah this needs to be a new issue. This one is closed.
