### ISSUE TITLE
Adding Encryption for Local SQLite and Remote Supabase

### ISSUE THREAD

**Issue by OneBillionth** [GetDutchie/brick#494]
Hello contributors 👋,

I want to say that I really like this package! I’m still learning and exploring its features, and I appreciate all the hard work that has gone into building it.

**I have a question regarding encryption for both local and remote databases.Is there an easy way or best practice to achieve encryption for both at the same time?** 

Specifically:
	1.	Can I integrate [sqflite_sqlcipher](https://pub.dev/packages/sqflite_sqlcipher) (or similar) for local data encryption?
	2.	For Supabase, are there any recommended workarounds or tools to encrypt data before storing or querying remotely?

Any suggestions, examples, or references would be greatly appreciated!

Thanks again for your time. 😊

**Comment by tshedor** [comment]
@OneBillionth

> 1. Can I integrate [sqflite_sqlcipher](https://pub.dev/packages/sqflite_sqlcipher) (or similar) for local data encryption?

Yes. This is a drop in replacement. Just pass the `databaseFactory` from the cipher package to all Brick constructors/methods that require it. If you're using Supabase, that's `SqliteProvider` and `OfflineFirstWithSupabaseRepository.clientQueue`. 

> 2. For Supabase, are there any recommended workarounds or tools to encrypt data before storing or querying remotely?

This is out of the domain for Brick. If you need to encrypt in transit, see if Supabase's client library supports anything like that and let me know.
