### ISSUE TITLE
Question - Is there a way to change the data after it is fetched

### ISSUE THREAD

**Issue by rlee1990** [GetDutchie/brick#496]
I wanted to know if there is a way to change data that might be fetched or inserted. 
Example:
Say you have a column called file_path and one that is called URL. 
If we wanted to split the data from file_path and use a supabase function that creates a public URL and returns as the URL column could we?
Also another example would be converting a string date and time to a type of DateTime?

**Comment by tshedor** [comment]
Yes, you can specify a custom `fromGenerator` in the `@Supabase` annotation

**Comment by rlee1990** [comment]
@tshedor thanks Is there any other examples on how to do this other than the custom generators one? Or does every generator need to be a map formate?

**Comment by rlee1990** [comment]
This is basically what I want to do but I don't see how both can be done in that same line:
```final split = currentUserSignal.value!.profilePhoto.filePath.split('/');
    url = StorageService()
        .getPublicUrl(bucket: split[0], name: '${split[1]}/${split[2]}');```

**Comment by tshedor** [comment]
```dart
StorageService().getPublicUrl(bucket: currentUserSignal.value!.profilePhoto.filePath.split('/')[0], name: '${currentUserSignal.value!.profilePhoto.filePath.split('/')[1]}/${currentUserSignal.value!.profilePhoto.filePath.split('/')[2]}');
```

**Comment by tshedor** [comment]
However, given what you're doing, I think you should be doing this using a computed getter instead: 

```dart
final String filePath;

@Sqlite(ignore: true)
String get url {
  final split = filePath.split('/');
  return StorageService().getPublicUrl(bucket: split[0], name: '${split[1]}/${split[2]}');
}
```

**Comment by hortigado** [comment]
Hi, regarding obtaining the URL, I think the recommended thing to do is to do it outside the brick environment, but anyway; using `fromGenerator `and `toGenerator` you need to add the function in the form of a string like in this example.
Model
![image](https://github.com/user-attachments/assets/7666cf05-05b6-4bff-9d4c-0ec3c25fce97)
Custom function
![image](https://github.com/user-attachments/assets/4d4a24bd-6eec-4db9-829b-86d39fc8ee49)
Result on adapter file
![image](https://github.com/user-attachments/assets/d71d43bf-100f-4a5d-b2dd-f9e6df7c55f3)

**Comment by rlee1990** [comment]
Thanks both of you.
