### ISSUE TITLE
Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by TillJohanndeiter** [GetDutchie/brick#497]
This is my generic component

```
class DbListener<T> extends StatelessWidget {
  final Stream<List<T>> stream;
  final Widget Function(List<T>) builder;

  const DbListener(this.stream, this.builder, {super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
      stream: stream,
      builder: (context, snapshot) {
        if (snapshot.data == null) {
          return SizedBox();
        } else {
          return this.builder(snapshot.data!);
        }
      },
    );
  }
}

```

For example i use it in contexts like this:

```

@override
  Widget build(BuildContext context) {
...
details = DbListener(
          Repository().subscribeToRealtime<UserProfile>(
              query: Query.where('id', selectedUserProfileId)),
          (userProfiles) {
            var selected = userProfiles
                .where((e) => e.id == selectedUserProfileId)
                .firstOrNull;

            return (selected == null)
                ? const SizedBox()
                : UserProfileDetail(
                    selected,
                    key: Key(selected.id),
                  );
          },
        );

```

During rebuilds of the widget i get this error

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Bad state: Stream has already been listened 
Sadly i cannot reproduce the error easily.
```

I already tried to convert the stream to a broadcast, but the error stays the same. In some contexts everything works fine, in other it constantly crashes at the first rebuild.

**Comment by tshedor** [comment]
Based on [the Flutter docs](https://api.flutter.dev/flutter/widgets/StreamBuilder-class.html):

> The [stream](https://api.flutter.dev/flutter/widgets/StreamBuilderBase/stream.html) must have been obtained earlier, e.g. during [State.initState](https://api.flutter.dev/flutter/widgets/State/initState.html), [State.didUpdateWidget](https://api.flutter.dev/flutter/widgets/State/didUpdateWidget.html), or [State.didChangeDependencies](https://api.flutter.dev/flutter/widgets/State/didChangeDependencies.html). It must not be created during the [State.build](https://api.flutter.dev/flutter/widgets/State/build.html) or [StatelessWidget.build](https://api.flutter.dev/flutter/widgets/StatelessWidget/build.html) method call when constructing the [StreamBuilder](https://api.flutter.dev/flutter/widgets/StreamBuilder-class.html).

Instead of creating the stream when this widget is created, are you able to create it either A) further up the tree before passing it to this widget or, more preferably, B) within a state manager like BLoC or Riverpod?

**Comment by TillJohanndeiter** [comment]
> Based on [the Flutter docs](https://api.flutter.dev/flutter/widgets/StreamBuilder-class.html):
> 
> > The [stream](https://api.flutter.dev/flutter/widgets/StreamBuilderBase/stream.html) must have been obtained earlier, e.g. during [State.initState](https://api.flutter.dev/flutter/widgets/State/initState.html), [State.didUpdateWidget](https://api.flutter.dev/flutter/widgets/State/didUpdateWidget.html), or [State.didChangeDependencies](https://api.flutter.dev/flutter/widgets/State/didChangeDependencies.html). It must not be created during the [State.build](https://api.flutter.dev/flutter/widgets/State/build.html) or [StatelessWidget.build](https://api.flutter.dev/flutter/widgets/StatelessWidget/build.html) method call when constructing the [StreamBuilder](https://api.flutter.dev/flutter/widgets/StreamBuilder-class.html).
> 
> Instead of creating the stream when this widget is created, are you able to create it either A) further up the tree before passing it to this widget or, more preferably, B) within a state manager like BLoC or Riverpod?

Thank your for the quick and helpful response! Now everything works fine! I use riverpod btw.

I added a new StreamProvider

```
final userIdSelectedStreamProvider = StreamProvider<List<UserProfile>>((ref) {
  final selectedUserId = ref.watch(userIdSelectedState);

  if (selectedUserId == null) {
    return const Stream<List<UserProfile>>.empty();
  }

  return Repository().subscribeToRealtime<UserProfile>(
    query: Query.where('id', selectedUserId),
  );
});
```

And I use the AsyncValue instead of the stream: 


```
        details = selectedUserStream.when(
            data: (data) {
              var selected =
                  data.where((e) => e.id == selectedUserProfileId).firstOrNull;

              return (selected == null)
                  ? const SizedBox()
                  : UserProfileDetail(
                      selected,
                      key: Key(selected.id),
                    );
            },
            error: (error, stackTrace) => Text(error.toString()),
            loading: () => const Center(child: PlatformProgressIndicator()));
```

**Comment by TillJohanndeiter** [comment]
After the change i have the problem that the widge rebuilds  constantly. Do you have any idea why?

```
class CommunityPage extends ConsumerWidget {
  const CommunityPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    var selectedUserProfileStream = ref.watch(selectedUserProfileProvider);
```

**Comment by tshedor** [comment]
I don't have enough code, but I would imagine that Riverpod is using equality comparisons and only reporting to the UI if the elements have changed. Do you have `Equatable` or `hashCode` overrides for your models and for the contents of `userIdSelectedState`?

**Comment by TillJohanndeiter** [comment]
> I don't have enough code, but I would imagine that Riverpod is using equality comparisons and only reporting to the UI if the elements have changed. Do you have `Equatable` or `hashCode` overrides for your models and for the contents of `userIdSelectedState`?

A child component created a stream in a  build method. I don't know why, but this caused the rebuilds.
