### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by rlee1990** [GetDutchie/brick#506]
I keep getting this error when trying to retrieve data from Supabase.
```type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>'```
I checked all adapters, and everythinther a string bool, int, or double. I really don't see what can be causing this.
This is the function I am running:
```dart
final data = await Repository().get<PostBrick>(
        query: Query(
          action: QueryAction.get,
          providerArgs: {
            'limit': 10,
            'offset': lastPostNumber,
            'orderBy': 'createdAt DESC'
          },
        ),
      );
```
I noticed that some post will return but most receive the above error. Checked each post and their related tabled and nothing as far as data types are different from the once that work and don't.

**Comment by tshedor** [comment]
@rlee1990 can you please provide a stack trace of the error? I'd like to see what line exactly it's throwing on. Also, for my own sanity, could you [please format your code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) with ```dart ?

**Comment by rlee1990** [comment]
@tshedor I am using the proper format it is showing as so for me in Github. Here is the stacktrace:
```
[log] #0      _$PostBrickFromSupabase (package:supabase_social_jawn_test/brick/adapters/post_brick_adapter.g.dart:32:98)
      <asynchronous suspension>
      #1      PostBrickAdapter.fromSupabase (package:supabase_social_jawn_test/brick/adapters/post_brick_adapter.g.dart:503:7)
post_brick_adapter.g.dart:503
      <asynchronous suspension>
      #2      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
future.dart:534
      <asynchronous suspension>
      #3      OfflineFirstRepository.hydrate (package:brick_offline_first/src/offline_first_repository.dart:457:32)
offline_first_repository.dart:457
      <asynchronous suspension>
      #4      OfflineFirstWithSupabaseRepository.hydrate (package:brick_offline_first_with_supabase/src/offline_first_with_supabase_repository.dart:119:14)
offline_first_with_supabase_repository.dart:119
      <asynchronous suspension>
      #5      OfflineFirstRepository.get (package:brick_offline_first/src/offline_first_repository.dart:207:16)
offline_first_repository.dart:207
      <asynchronous suspension>
      #6      OfflineFirstWithSupabaseRepository.get (package:brick_offline_first_with_supabase/src/offline_first_with_supabase_repository.dart:96:14)
offline_first_with_supabase_repository.dart:96
      <asynchronous suspension>
      #7      _HomeState.fetchPost (package:supabase_social_jawn_test/features/home/pages/home.dart:236:20)
home.dart:236
      <asynchronous suspension>
```

**Comment by tshedor** [comment]
Your markdown is just `` ``` ``; please add `` ```dart ``.

Thank you for the stack trace. What's the content of `post_brick_adapter.g.dart:32`?

**Comment by rlee1990** [comment]
This is the content for the fromSupabase part:
```dart
Future<PostBrick> _$PostBrickFromSupabase(Map<String, dynamic> data,
    {required SupabaseProvider provider,
    OfflineFirstWithSupabaseRepository? repository}) async {
  return PostBrick(
      postText: data['post_text'] as String?,
      hasFile: data['has_file'] as bool,
      isPinned: data['is_pinned'] as bool,
      isLocationPost: data['is_location_post'] as bool,
      toExpire: data['to_expire'] as bool,
      createdAt: data['created_at'] as String,
      updatedAt: data['updated_at'] as String,
      locationData: data['location_data'] as String?,
      postHashtag: await Future.wait<PostHashtagBrick>(data['post_hashtag']
              ?.map((d) => PostHashtagBrickAdapter()
                  .fromSupabase(d, provider: provider, repository: repository))
              .toList()
              .cast<Future<PostHashtagBrick>>() ??
          []),
      postFile: await Future.wait<PostFileBrick>(
          data['post_file']?.map((d) => PostFileBrickAdapter().fromSupabase(d, provider: provider, repository: repository)).toList().cast<Future<PostFileBrick>>() ??
              []),
      postMention: await Future.wait<PostMentionBrick>(data['post_mention']
              ?.map((d) => PostMentionBrickAdapter().fromSupabase(d, provider: provider, repository: repository))
              .toList()
              .cast<Future<PostMentionBrick>>() ??
          []),
      reactions: await Future.wait<PostReactionBrick>(data['reactions']?.map((d) => PostReactionBrickAdapter().fromSupabase(d, provider: provider, repository: repository)).toList().cast<Future<PostReactionBrick>>() ?? []),
      user: await PostUserBrickAdapter().fromSupabase(data['user'], provider: provider, repository: repository),
      sharedPost: data['shared_post'] == null ? null : await PostBrickAdapter().fromSupabase(data['shared_post'], provider: provider, repository: repository),
      id: data['id'] as String?);
}
```

**Comment by tshedor** [comment]
@rlee1990 which is line 32?

**Comment by rlee1990** [comment]
@tshedor 
```dart
sharedPost: data['shared_post'] == null ? null : await PostBrickAdapter().fromSupabase(data['shared_post'], provider: provider, repository: repository),
```

**Comment by tshedor** [comment]
@rlee1990 Great, thank you. This is what I was worried about. I don't believe Brick is capable of making a self-referential model. And if it were capable, I think Supabase's PostgREST will return this as a List even if just one item is available.

I'd be surprised if this is `null` for all posts because Supabase is definitely sending you data, otherwise you wouldn't have this parse issue. Also there's a `foreign_key` not named with a typical convention (`post_author` instead of `post_author_id`), so I'd verify you're using the right column.

Your best bet here is to 1) store the value as a primitive (`final int? sharedPostId`) and query on it when you need it 2) define it as `final List<PostBrick>? sharedPost`

**Comment by rlee1990** [comment]
@tshedor here are the columns from supabase and here is the data for shared_post_id column in supabase:
![Screenshot 2024-12-19 at 1 40 33 PM](https://github.com/user-attachments/assets/860f6556-54fb-447f-9022-b4f5f20f74c3)
![Screenshot 2024-12-19 at 1 40 51 PM](https://github.com/user-attachments/assets/f37a73b7-417a-4a51-983d-9548b8cbcffb)

**Comment by tshedor** [comment]
Yes, but if Dart is throwing on this line, the data it receives from Supabase is definitely not null

**Comment by rlee1990** [comment]
@tshedor Ill try doing it with out it. It's odd though because before yesterday It worked for the post then I made a change to comments and then I started having this issue with every post.
I guess that will be the same issue with comments and others that I am using.

**Comment by rlee1990** [comment]
I do have another question.
Is it possible for range filter to be added? If not it's fine I have a workaround that I am using just thought I would ask @tshedor

**Comment by rlee1990** [comment]
Thanks.
