### ISSUE TITLE
Support for Converting Map<String, dynamic> to Custom Models Dynamically

### ISSUE THREAD

**Issue by OneBillionth** [GetDutchie/brick#507]
I am storing a Map<String, dynamic> field (e.g., data) in my table, but I want to convert it dynamically into custom model classes **(like PhotoData, VideoData, AudioData, NoteData, etc.)** based on another field, such as an `enum` type.

Is there a recommended approach in `brick_offline_first_with_supabase` to:
	1.	Convert a `Map<String, dynamic>` to specific Dart model classes dynamically during fetching?
	2.	Convert back from the model classes to `Map<String, dynamic>` before inserting or updating?

Example structure:
	•	data (stored as `Map<String, dynamic>`)
	•	type (an `enum`, e.g., photo, video, note, audio)

Would appreciate any suggestions or best practices for handling this use case!

**Comment by hortigado** [comment]
> you can use a custom fuction and pass the map to it to return the model by the type. How it example in rest
 ![imagen](https://private-user-images.githubusercontent.com/42924254/395640214-7666cf05-05b6-4bff-9d4c-0ec3c25fce97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NDY3NjksIm5iZiI6MTczNDY0NjQ2OSwicGF0aCI6Ii80MjkyNDI1NC8zOTU2NDAyMTQtNzY2NmNmMDUtMDViNi00YmZmLTlkNGMtMGVjM2MyNWZjZTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDIyMTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMDhjYzcwNDNmZDYzY2Y5ZDU1MGU2YTgzY2NlMjIyMzE5YjUyMDlmYjIzZDk0OWU0YzlmOWY1NDNkZmRmOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ro99iZ-vJhNw-t5AJEBxBA9FZaS85urYoM2t1T7pmoc) ![imagen](https://private-user-images.githubusercontent.com/42924254/395636893-4d4a24bd-6eec-4db9-829b-86d39fc8ee49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NDY3NjksIm5iZiI6MTczNDY0NjQ2OSwicGF0aCI6Ii80MjkyNDI1NC8zOTU2MzY4OTMtNGQ0YTI0YmQtNmVlYy00ZGI5LTgyOWItODZkMzlmYzhlZTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDIyMTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMjRiMGM2M2NmYjkxNzJjZWM4MTMxOGM2MmIwNGFhOTFkYzk0YThkZmM2ODU1NzM0ZWY0MWEzMGVmZjlhOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cYV3f015uO4a58F8_Btd8w5LMZoolKyCRVUqoV0ss68) ![imagen](https://private-user-images.githubusercontent.com/42924254/395634240-d71d43bf-100f-4a5d-b2dd-f9e6df7c55f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NDY3NjksIm5iZiI6MTczNDY0NjQ2OSwicGF0aCI6Ii80MjkyNDI1NC8zOTU2MzQyNDAtZDcxZDQzYmYtMTAwZi00YTVkLWIyZGQtZjllNmRmN2M1NWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDIyMTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNWNjMThiYWYwODBjYjkxZmVhNjFlZDZkOWE5MTlkMmE1ZThhODg2OTExMmM5MTBlM2VhZDY1NjcwMTFkYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g0Q6piULRGv9KodQG9BXx77ZEyKSrr3k0V1TaHBHdk8)

**Comment by tshedor** [comment]
@OneBillionth I would [recommend using an OfflineFirstSerdes](https://getdutchie.github.io/brick/#/offline_first/models?id=offlinefirstserdes). This will allow you to specify your own `fromSupabase` and `toSupabase` in the Dart code on the class.

**Comment by OneBillionth** [comment]
@tshedor thanks, I tried using `OfflineFirstSerdes` with custom `fromSupabase` and `toSupabase` methods to handle dynamic deserialization of the data field. 

However, Brick still doesn’t generate the field correctly, resulting in **a missing argument error**. Is there a specific configuration or example for handling dynamic JSON fields like this?

**Comment by OneBillionth** [comment]
@tshedor thanks, figured it out!
