### ISSUE TITLE
 type 'int' is not a subtype of type 'double?' in type cast

### ISSUE THREAD

**Issue by richard457** [GetDutchie/brick#512]
I often face this issue, it seems like setting a field as double causes trouble when upserting.
```dart
@ConnectOfflineFirstWithSupabase(
  supabaseConfig: SupabaseSerializable(tableName: 'tables'),
)
class Table extends OfflineFirstWithSupabaseModel {
  @Sqlite(unique: true, index: true)
  @Supabase(unique: true)
  final int id;
  DateTime? deletedAt;
  @Sqlite(defaultValue: "18.0")
  @Supabase(defaultValue: "18.0")
  double? rolePercentage;
}

**Comment by richard457** [comment]
I deleted all migration and re-created but the error shifted from one model to another.

**Comment by richard457** [comment]
also learned that saving 0.0 will be 0 finally which will cause the error as well.

**Comment by tshedor** [comment]
You should use `num` instead of double. Supabase's API sends whole numbers if they're stored without decimals. `num` won't change the SQLite column but it will change the adapter to be more flexible.

**Comment by richard457** [comment]
Thank you very much, that helped.
