### ISSUE TITLE
Faile to save a child Model -> final Variant variant; within Stock model.

### ISSUE THREAD

**Issue by richard457** [GetDutchie/brick#513]
When defining relationship I get the issue when upserting model with relationship
```dart
class Stock extends OfflineFirstWithSupabaseModel {
  @Sqlite(unique: true, index: true)
  @Supabase(unique: true)
  final int id;

  /// this variant_id need to be set as foreign key
  /// ALTER TABLE stocks
  /// ADD CONSTRAINT fk_variant_id
  /// FOREIGN KEY (variant_id) REFERENCES variants(id);

  @Supabase(foreignKey: 'variant_id')
  final Variant variant;

  // If the association will be created by the app, specify
  // a field that maps directly to the foreign key column
  // so that Brick can notify Supabase of the association.
  @Sqlite(ignore: true)
  int get variantId => variant.id;
```
and

```dart
class Variant extends OfflineFirstWithSupabaseModel {
  @Sqlite(unique: true, index: true)
  @Supabase(unique: true)
  final int id;
  @Supabase(nullable: true, ignore: true)
  @Sqlite(nullable: true, ignore: true)
  Stock? stock;

  @Supabase(nullable: true, ignore: true)
  @Sqlite(nullable: true, ignore: true)
  int? stockId;
```

I don't know what I am doing wrong, your help is much appreciated.

**Comment by richard457** [comment]
<img width="1755" alt="image" src="https://github.com/user-attachments/assets/c7920843-4eb0-41ae-9502-a7cf49b41e5b" />

**Comment by richard457** [comment]
I realized that the issue is field final Variant variant; being passed to recursiveAssociationUpsert( and is not known by modelDictionary it fail at line 
```dart
 assert(modelDictionary.adapterFor.containsKey(type), '$type not found in the model dictionary');

```

**Comment by tshedor** [comment]
@richard457 please format the title of this issue appropriately for others to more easily interpret it. The stack trace should be in the body of the issue, not the title. 

Regarding the issue, are you sure that the assert is throwing on the Variant model? 

I would also avoid this recursive association and only pick one parent->child direction https://getdutchie.github.io/brick/#/offline_first/offline_first_with_supabase_repository?id=recursivelooped-associations

**Comment by richard457** [comment]
Thanks, Let me keep investigating about the provided link, I appreciate your help.
